### ISSUE TITLE
Improve clarity of allowedOrigins in VerificationObject

### ISSUE THREAD

**Issue by jbohrer** [IMSGlobal/openbadges-specification#162]
The current description for the [allowedObjects](https://www.imsglobal.org/sites/default/files/Badges/OBv2p0/index.html#allowedOrigins) property is slightly incomplete and can be improved by adding the following to the description:
- Clarify that hostname component does include subdomains and ports
- Explicitly stating support for an array of hostnames
- Provide link to hostname component standard ([RFC952](https://tools.ietf.org/html/rfc952)?)

These suggestions were identified by the IMS Open Badges Workgroup.

**Comment by mgylling** [comment]
Markus will provide a PR for review on next meeting.

**Comment by mgylling** [comment]
See PR #170

**Comment by mgylling** [comment]
Fixed in #170
