### ISSUE TITLE
Clarification: Allow use of Image class in Issuer Profile

### ISSUE THREAD

**Issue by ottonomy** [IMSGlobal/openbadges-specification#165]
The image property under [Profile](https://www.imsglobal.org/sites/default/files/Badges/OBv2p0/index.html#Profile) currently reads:

| Property | type | Description
| -- | -- | -- |
| image | Data URI or URL | An image representing the issuer.

It should read, to match BadgeClass:

| Property | type | Description
| -- | -- | -- |
| image | @id: Image | An image representing the issuer. May be a Data URI, or URI where the image may be found or instance of the Image class.

This would clarify that instances of the new-to-2.0 [Image](https://www.imsglobal.org/sites/default/files/Badges/OBv2p0/index.html#Image) class may be used, allowing issuers to include a caption or other metadata for accessibility.

**Comment by mgylling** [comment]
@ottonomy We reviewed this on todays call. We are thinking that the best option may be to leave the type field as is, and change the description to your new proposed text. This will avoid people interpreting the table to mean one can only point to image classes. Thoughts?

**Comment by ottonomy** [comment]
@mgylling Sorry I couldn't make the call. A bit of a bout with food poisoning that morning. 

The proposed value for "type" in this table is how we've done it for BadgeClass and Assertion. It seems weird to do it two different ways. "type": "@id" means that the value should identify another JSON-LD subject, either as an embedded node in the JSON or by an IRI (and then we make the clarification that data URIs are also acceptable). If how we've done it for [BadgeClass](https://www.imsglobal.org/sites/default/files/Badges/OBv2p0/index.html#BadgeClass) and Assertion is confusing, then we should resolve that, but as a separate issue. IMHO.

**Comment by mgylling** [comment]
@ottonomy Got it re being consistent. PR #169 for review on todays call.
