### ISSUE TITLE
finalize primitive datatypes section

### ISSUE THREAD

**Issue by mgylling** [IMSGlobal/openbadges-specification#167]
We've noted before that the three first entries in the list at [Primitive Datatypes](https://www.imsglobal.org/sites/default/files/Badges/OBv2p0/index.html#primitive-datatypes) needs to be defined. Somehow this got lost.

**Comment by ottonomy** [comment]
`Array` is actually probably now how we want to describe lists of things because JSON-LD treats single instance in a set the same as a single instance not in a set when compacting. We probably want to describe for each property where multiple values are allowed that there are multiple instances of whatever value type is expected allowed.

**Comment by mgylling** [comment]
We will fix all occurrences of arrayness in the spec properly. Alex will start with producing a list of all properties that can be arrays (including allowedOrigins which currently is ambiguous in this regard). The datatypes section will then be updated to have a referenceable definition for array-or-single-item.

**Comment by ahripak** [comment]
My survey of the arrayable fields:

Assertion
- evidence

BadgeClass
- alignment
- tags

VerificationObject
- allowedOrigins

RevocationList
- revokedAssertions

Several classes
- related

It feels necessary to have a second or even third person validate this list—quite possible I missed one.

**Comment by mgylling** [comment]
Nate: endorsement should be added as well

**Comment by ottonomy** [comment]
"type" fields may also allow many. When Profile is used as an Expected Recipient Profile (not as an issuer profile), several additional properties may allow many, but that probably doesn't need to be remarked on, because it would just be confusing..

**Comment by ottonomy** [comment]
Proposed on the call with no objections: We will add "(Multiple values allowed)" to the expected type column for all the properties listed above.

**Comment by mgylling** [comment]
@ottonomy Yes, that works. Do you want to propose a replacement for the "Array" entry in the datatypes section as well? My suggestion would also be that for ultimate clarity, each occurrence of  "(Multiple values allowed)" would be a link to that new definition of array-or-plain-value...

**Comment by ottonomy** [comment]
@mgylling how about: "Array - A JSON array as defined in RFC4627 should be used for all properties where multiple values are allowed. Each entry in the array should match the type requirement specified for that property."

**Comment by mgylling** [comment]
Fixed in #176
