### ISSUE TITLE
Update the Assessment Extension to add Rubric and Section/Question data

### ISSUE THREAD

**Issue by ottonomy** [IMSGlobal/openbadges-specification#171]
A use case has been identified to add additional information about assessment(s) in a BadgeClass. 

As an issuer:
* I would like to define one or more Rubrics that I will use to assess a submission for badge award. I would like to publish these in the badge metadata
* I would like to define a structured set of questions that I use to publish an application for a badge. These questions should be visible to potential applicants, to my assessment application tracking system, and to consumers of the badge who want to find out what recipients had to submit in order to apply for it.

Here is a data model that relies on CASE rubrics that could be used to serve these use cases:
![assessmentextension-data-model-proposed-update-2018-v2](https://user-images.githubusercontent.com/2304883/35531503-10a49774-04ec-11e8-981c-96e373304fb4.png)

Additionally, we might take the opportunity to fix a few bugs with the AssessmentExtension:
* Update JSON-schema to adapt to how validation will actually occur (the JSON-LD compacted into `{"@context": ["https://w3id.org/openbadges/v2", "THE EXTENSION CONTEXT"]}` so that successful implementations may be made that only have one value for "assessment"
* Potentially update to add the alias "assessments" for "assessment"
* Switch the "assessmentType" from being a string from an enumeration of acceptable values to use the JSON-LD native `@type` (aliased as `type` in the Open Badges v2 context). Define the three types `Performance`, `Exam`, and `Artifact` as IRIs in the extension context. Update schema to match. This would better match how other parts of the Open Badges Spec are implemented to take advantage of native JSON-LD features. See IdentityObject for one example.

**Comment by jbohrer** [comment]
Incorporated via #175
