### ISSUE TITLE
IssuerAccreditation Extension Review Issues

### ISSUE THREAD

**Issue by cawjustin** [IMSGlobal/openbadges-specification#179]
Propose to use this as a catch-all to discuss any issues.

**First issue:** We are missing a property to describe the country of the accrediting organization. Address fields currently include locality (city), region (state), and postal code. But not country.

We should add a string property for `addressCountry`

**Comment by jbohrer** [comment]
Per workgroup call 3/15/2018:
- Canonical location: http://imsglobal.github.io/openbadges-specification/extensions/issuerAccreditationExtension/index.html 
- Also need to publish as Respec doc

**Comment by ViktorHaag** [comment]
- Should "educationSector" values be in an enumerated, standard vocabulary?
- Should there be a "contactEmail" property for the organization?

**Comment by mgylling** [comment]
A better link for location: https://rawgit.com/IMSGlobal/openbadges-specification/master/extensions/issuerAccreditationExtension/index.html

**Comment by jbohrer** [comment]
Yes, use existing schema: email found in OBv2 context file

**Comment by jbohrer** [comment]
Added via #191
