### ISSUE TITLE
Bug in how the validatesType is described in the spec

### ISSUE THREAD

**Issue by ottonomy** [IMSGlobal/openbadges-specification#180]
This property is described as following:

validatesType | string/compact IRI | Valid JSON-LD type for a badge component, such as Assertion, extensions:ApplyLink, or https://w3id.org/openbadges/extensions#ApplyLink. Compact forms preferred.

This property should actually be described as:
"JSON-LD type as it appears compacted into the Open Badges context"

This change enables extension authors to accurately understand how to build their extension context file so that the validator will match the extension node to the correct JSON-schema validator.

**Comment by jbohrer** [comment]
Workgroup 9/27 general agreement to be included in future Errata document.
