### ISSUE TITLE
Endorsement class description missing revocation info

### ISSUE THREAD

**Issue by ottonomy** [IMSGlobal/openbadges-specification#208]
Endorsements are verified just like Assertions are and they may be revoked at any time just like Assertions, using the same methods. If delivered with `SignedBadge` verification type, they may appear on an issuer's RevocationList. If delivered with `HostedBadge` verification, the canonical record may be replaced with a representation of the revoked status just like a hosted Assertion:
```jsonld
{
  "@context": "https://w3id.org/openbadges/v2",
  "type": "Endorsement",
  "revoked": true,
  "revocationReason": "changed our minds"
}
```

I think this is essentially errata, so I applied that label for now. For discussion in workgroup.

**Comment by davidlj95** [comment]
Totally agree

**Comment by ahripak** [comment]
The issue has been addressed and merged. We'll work to get this change deployed.
