### ISSUE TITLE
Broken link for Endorsement Framework

### ISSUE THREAD

**Issue by davidlj95** [IMSGlobal/openbadges-specification#215]
The Endorsement Framework link in the Endorsement section (https://github.com/IMSGlobal/openbadges-specification/blame/master/index.md#L457) is broken. I can't find the proper link for it.

**Comment by ottonomy** [comment]
[Badge Endorsement Getting Started - Badge Alliance.pdf](https://github.com/IMSGlobal/openbadges-specification/files/2954708/Badge.Endorsement.Getting.Started.-.Badge.Alliance.pdf)

Yes, unfortunately the Google Drive link broke but here's the file. It is not currently uploaded on the web. Licensed CC-BY: It can be uploaded somewhere official enough, and the link can be recreated.

**Comment by davidlj95** [comment]
Awesome @ottonomy, thanks!
