### ISSUE TITLE
Will the validator accept Base64 in criteria and evidence narrative properties?

### ISSUE THREAD

**Issue by kayaelle** [IMSGlobal/openbadges-specification#222]

**Comment by justinpitcher** [comment]
Side note that the validator is tracked separately:
https://github.com/IMSGlobal/openbadges-validator-core/issues

I'm not sure I understand the question. Are you asking if a Base64 encoded value will trigger an error? Without checking, I don't see how it would cause any errors as a string is a string. It would be unusable to a displayer/consumer, but it would be valid data.

**Comment by ottonomy** [comment]
@justinpitcher is right. Those values are nonsensical in terms of the stated purpose of those fields, but they would not disrupt the validity of the badge. :)
