### ISSUE TITLE
IMS OpenAPI generator cannot generate simple list schema for POST /assertions endpoint

### ISSUE THREAD

**Issue by amiller-ims** [IMSGlobal/openbadges-specification#241]
This is a limitation of the IMS generator, not of OpenAPI Schema, but is not a high priority to fix.

Endpoint description:

> Create or update an Assertion. Multiple Assertions are not allowed. Data MUST be a list exactly one Assertion long. JWS-signed Assertions must be represented in the JSON serialization option.

If the description were changed to pass the assertion directly (not in a list) there would be no problem.

If we want to keep the list format, Colin recommends wrapping the list in an object such as:
```
{
  "assertions": [
    {...assertion...}
  ]
}
```

**Comment by ottonomy** [comment]
In JSON-LD a list `"assertions": [{ASSERTION...}]` and `"assertions": {ASSERTION...}` are equivalent. We make the recommendations like the above to ease processors that want to process in "JSON-only" at this level.

In general, today's short-term limitations of the autogeneration code should not block correct API design, but as we revised the response envelope to be less consistent across different endpoints already, I would not be against revising the recommendation from:

> Create or update an Assertion. Multiple Assertions are not allowed. Data MUST be a list exactly one Assertion long. JWS-signed Assertions must be represented in the JSON serialization option.

to something like: 

> Create or update an Assertion. Multiple Assertions are not allowed. If successful, one assertion MUST be returned in the appropriate format. If the resultant assertion is a JWS, it MUST be expressed in compact serialization as a value of the "compactJws" property. Otherwise, the resultant assertion MUST be expressed as JSON as a value of the "assertions" property. In both cases, the value MUST not be enclosed in a JSON array.


This also resolves inconsistency between different endpoints about JWS presentation.

**Comment by amiller-ims** [comment]
So without changing the current description, the OpenAPI schema could model the POST payload (the JSON in the body of of the POST request) as:
```
{ASSERTION...}
```
And JSON-LD processors would see this as conforming with the current description. Is that right?

Similarly if the endpoint returned a payload like:
```
{ASSERTION...}
```

JSON-LD processors would see this as conforming with the current description.

Would the above two statements still be true if the description were changed as you suggest?
