### ISSUE TITLE
Update IdentityObject Description for Type

### ISSUE THREAD

**Issue by kayaelle** [IMSGlobal/openbadges-specification#254]
The description for type includes the line: "Currently the only supported value for many platforms that implement Open Badges is email, but other properties are available."

Please change to: "Currently the only supported values for many platforms that implement Open Badges are email and url, but other properties are available."

or perhaps just remove it?

Thanks!

**Comment by justinpitcher** [comment]
I can't change the assignee to me, but I'll take a stab at this.

**Comment by ahripak** [comment]
Hi @kayaelle! Just a heads up we're intending to make [some small copy changes](https://github.com/IMSGlobal/openbadges-specification/pull/277) related to this issue. If you have feedback that would be most appreciated.

**Comment by kayaelle** [comment]
I like it! Thanks!

**Comment by ahripak** [comment]
Thanks, Kerri! This is now merged into `develop` and we'll work towards getting it published.
