### ISSUE TITLE
Response Envelope Clarity

### ISSUE THREAD

**Issue by justinpitcher** [IMSGlobal/openbadges-specification#255]
A recent conversation about Badge Connect made me realize we have small pitfall perhaps in our documentation.

The Response Envelope section says

> Responses from **all** APIs in this document are wrapped in a JSON envelope.

And then shows our response JSON format. However, the first endpoint that is documented is the client registration. It's the first endpoint to use from the manifest, but is in fact a standardized response (RFC 7591). We don't display an example response, leaving some room for interpretation.

In the conversation I had there was a small misunderstanding at first that the response envelope applied to client registration.

We should consider tweaking the language to explicitly say it does not apply to oauth-related endpoints.

**Comment by ottonomy** [comment]
👍 to updating this language to refer only to Badge Connect data endpoints

**Comment by ahripak** [comment]
+1 to this—and I think in discussion with @andyfmiller we both agreed that a clarification should be made.
