### ISSUE TITLE
extraDescription Extension Link Broken

### ISSUE THREAD

**Issue by ottonomy** [IMSGlobal/openbadges-specification#256]
There is a link to the extra description extension in https://github.com/IMSGlobal/openbadges-specification/blob/develop/ob_v2p0/extensions/index.md that points to the wrong page. When this was included in commit 21b0999b, IMS was publishing a spec preview on GitHub pages, which has since been discontinued, so now this link is broken, and IMS has not republished the relevant materials to the canonical location. 

There is a html file in the repository latest develop branch here: https://github.com/IMSGlobal/openbadges-specification/tree/develop/ob_v2p0/extensions/extraDescription

But it is not published alongside the spec. I.e. if you go to https://openbadgespec.org/extensions/extraDescription/index.html you are redirected back to the main spec. 

A publishing workflow should be implemented so that there is a clear and understandable relationship between the contents of the git repository and the published materials. This should cover the use case for publishing extensions that IMS has requested be published as part of this community- and member-contributed extensions page.

**Comment by jbohrer** [comment]
Resolved in #270
