### ISSUE TITLE
BadgeClass and Issuer image fields are not specific about what image formats are acceptable

### ISSUE THREAD

**Issue by ottonomy** [IMSGlobal/openbadges-specification#257]
The Assertion image field (correctly) says for its description:

> IRI or document representing an image representing this user’s achievement. This must be a PNG or SVG image, and should be prepared via the Baking specification. An ‘unbaked’ image for the badge is defined in the BadgeClass and should not be duplicated here.

The BadgeClass image field says for its description: 

> IRI of an image representing the achievement. May be a Data URI, or URI where the image may be found.

The Issuer/Profile image field says for its description:

> An image representing the issuer. May be a Data URI, or URI where the image may be found or an instance of the Image class.

---

The BadgeClass image should probably match the requirements of the Assertion in filetype, because otherwise the baking operation would require a filetype conversion as well. Only PNG and SVG images are eligible for baking under the current spec.

The Issuer/Profile image could stand some clarification even if we decide to explicitly allow other filetypes, just as a help to developers implementing roles where they have to display issuer information that they did not author. Additionally, looks like a couple words like "representing the issuer" survived a process where we made the class a bit more generic (to cover other cases of representing profiles like recipients etc) and still refer to an implementation of this class as the issuer.

**Comment by hadyrashwan** [comment]
I support the standardization  of image fields on PNG and SVG. Just like how it's done in badge image(open badges 2.0)
