### ISSUE TITLE
OB 2.1 Spec: Missing Data-Type Definition for the Data Models

### ISSUE THREAD

**Issue by ColinSmythe** [IMSGlobal/openbadges-specification#304]
In many parts of the OB 2.1 speculation there are no definitions of the data-type for the properties. This must be corrected.  Each property definition MUST have its data-type defined and value space. Use of the JSON data-types is insufficient because these do not provide a good enough definition.  IMS has a clearly defined set of standard data-types to use. Poor data-typing leads to bad interoperability.
The set of data-types themselves should be clearly defined in the specification document.

**Comment by ottonomy** [comment]
This is a bit late in the process for this consideration for 2.1, but it would be a good consideration for 3.0.
