### ISSUE TITLE
OB 2.1 Spec: Unclear Multiplicity of Properties

### ISSUE THREAD

**Issue by ColinSmythe** [IMSGlobal/openbadges-specification#305]
The OB 2.1 multiples for the data-types is unclear.  It appears that the use of the word 'array' is used to denote a multiplicity of more than one. It would be more clear if the 'Required' columns include the multiplicity.  For example, the value space for the Required column could be: Yes, No, Yes(Array), No (Array).  Alternative vocabs or approaches would work as well.

**Comment by ottonomy** [comment]
I suggest that we don't worry about this one for 2.1 but that this would be something we'll naturally consider for 3.0.
