### ISSUE TITLE
OB 2.1: Bad Practice Payload Use of 'Null' Values

### ISSUE THREAD

**Issue by ColinSmythe** [IMSGlobal/openbadges-specification#306]
In the OB 2.1 specification there are recommendations of using 'null' values.  For example:
{
    "assertion": { ... },
    "signedAssertion": null
  }

This is bad practice and leads to poor interoperability and data integrity.  In most cases a 'null' value is a data-type violation.
Instead the property must be defined as optional and if there is no data the property must not be present in the payload. We have started to create best practices on this in our FAQ store at: [https://support.imsglobal.org/a/solutions/articles/48001171022]

**Comment by ottonomy** [comment]
I recommend that this be closed and set aside for the next version. This is a significant structural change that would have been a worthwhile architecture question to discuss a couple years ago, but this would be a disruptive change now. We can accommodate this feedback in 3.0.
