### ISSUE TITLE
OB 2.1 Spec: Missing Substring on Endpoint Labelling

### ISSUE THREAD

**Issue by ColinSmythe** [IMSGlobal/openbadges-specification#307]
In the OB 2.1 specification the endpoints do not include documentation of the required use of baseURL substring of "/ims/ob/v2p1". Addition of this substring brings OB 2.1 into  alignment with the other IMS specifications e.g. CASE, CLR,  OneRoster, etc. The Conformance & Certification already includes the correct required use of this substring.
This naming convention is used to guarantee differentiation between the many endpoints defined by IMS in set of service-based specifications.

IMS uses a naming convention for the ‘baseURL’ part of the URLs defined for endpoints. This ‘baseURL’ naming convention has three parts:

- The substring ‘ims’ to identify the endpoint as specified by IMS;
- The short name of the specification for which the endpoint is being defined e.g. ‘or’ for  OneRoster, ‘ob’ for Open Badges, etc.
- The version of the endpoint e.g. ‘v1p0’, 'v2p1', etc.  IMS use major and minor versioning as per Semantic Versioning (in some cases IMS do use minor versioning when backwards compatibility is violated).

In the case of the OpenBadges 2.1 endpoints this means that the ‘baseURL’ is: ‘/ims/ob/v2p1’. Therefore in OB 2.1 the endpoints have a URL format of ‘<…hostname…>/ims/ob/v2p1/assertions’ etc.

The justifications for this approach are:

- Versioning of the URL endpoints is well established best practice.  Major and minor numbering is used by IMS because not all minor revisions maintain backwards compatibility;
- The ‘baseURL’  approach makes it easier to avoid endpoint name clashes i.e. when the same endpoint URL leaf name is used by more than one IMS specification;
- The ‘baseURL’ approach enables the Consumer to control and predict the payloads that MUST be supplied;
- The ‘baseURL’ approach provides a reference place for the location of service discovery information.

**Comment by ottonomy** [comment]
In the above `‘<…hostname…>/ims/ob/v2p1/assertions’`, this should be change to `‘<…apiBase…>/ims/ob/v2p1/assertions’`
