### ISSUE TITLE
OB 2.1 Spec: There is no description of the OpenAPI (YAML)

### ISSUE THREAD

**Issue by ColinSmythe** [IMSGlobal/openbadges-specification#309]
In the specification there is a link to the OB 2.1 OpenAPI (YAML) file but no supporting descriptive/explanatory text.  These OpenAPI files are important IMS artefacts and these need to be described and their relevance/usage explained.

**Comment by ottonomy** [comment]
It is better not to have an additional document to serve this purpose, but an additional paragraph could theoretically be added to the spec doc to link again to YAML and/or JSON format OpenAPI file and describe the purpose for which those files are available.
