### ISSUE TITLE
OB 2.1 Spec: No Description of the JSON-LD Context File

### ISSUE THREAD

**Issue by ColinSmythe** [IMSGlobal/openbadges-specification#310]
In the specification there is a link to the OB 2.1JSON-LD Context File file but no supporting descriptive/explanatory text.  These Context files are important IMS artefacts and these need to be described and their relevance/usage explained.

**Comment by ottonomy** [comment]
There is this whole document that is explanatory that is linked from the main spec https://purl.imsglobal.org/spec/ob/v2p1/context/

I would very much prefer there not being this type of document in the specification document set.

Recommend to close this ticket.
