### ISSUE TITLE
Reconcile Achievement required properties (cardinality)

### ISSUE THREAD

**Issue by danblickensderfer** [IMSGlobal/openbadges-specification#342]
Repurposing this issue to review and reconcile the Achievement class definition in [common_credentials.lines](https://github.com/IMSGlobal/openbadges-specification/blob/develop/ob_v3p0/common_credentials.lines#L31-L47).

In [OB 2.0](https://www.imsglobal.org/sites/default/files/Badges/OBv2p0Final/index.html#BadgeClass), `id`, `type`, `name`, `description`, `image`, `criteria`, and `issuer` are required. And `type` is an array.

In [CLR 1.0](https://www.imsglobal.org/sites/default/files/spec/clr/v1p0/InfoModel/clr_InfoModel.html#Data_Achievement), only `id` and `name` are required. And `type` is not an array.

Typically it is a good idea to adopt the more restrictive cardinality. That can improve interoperability (consumer know what fields they can depend on).

This should be discussed in a joint meeting.

**Comment by amiller-ims** [comment]
Currently, the [Achievement data model](https://imsglobal.github.io/openbadges-specification/ob_v3p0.html#achievement-0) has a `creator` property (replacing the `issuer` property from OB 2.0), and the [AssertionCredential data model](https://imsglobal.github.io/openbadges-specification/ob_v3p0.html#assertioncredential) has a `issuer` property.

**Comment by kayaelle** [comment]
The creator property makes it possible for an achievement to be described by one entity and issued by a separate entity. That doesn't need to be true, it could continue to be the same entity. 

We should discuss whether creator is implied by the issuer id if not explicitly included or if it should be required. 

A VC Issuer must be a URI or an object containing ID property.  "It is RECOMMENDED that the [URI](https://www.w3.org/TR/vc-data-model/#dfn-uri) in the [issuer](https://www.w3.org/TR/vc-data-model/#dfn-issuers) or its id be one which, if dereferenced, results in a document containing machine-readable information about the issuer that can be used to [verify](https://www.w3.org/TR/vc-data-model/#dfn-verify) the information expressed in the [credential](https://www.w3.org/TR/vc-data-model/#dfn-credential)." [https://www.w3.org/TR/vc-data-model/#issuer](https://www.w3.org/TR/vc-data-model/#issuer).

Most wallets specifically require the issuer value to be a did that correlates to the key used to sign the credential. A creator property value could be a DID but it won't be used to verify the badge. In instances where there is a separate creator entity and when more information is requested of the issuer, we can consider aligning with the CTDL [CredentialOrganization](https://credreg.net/ctdl/terms/CredentialOrganization#CredentialOrganization) subclass properties to increase ecosystem interoperability.

**Comment by amiller-ims** [comment]
An Achievement reconciliation issue was created in [CLR](https://github.com/IMSGlobal/ComprehensiveLearnerRecord/issues/280). But since the resolution will be made in common_credentials.lines, it is better to track it in this repo.

@martyr280 provided the only feedback before I closed the other issue:
```
image should not be required, I agree with the other requirements.
```

**Comment by debeverhart** [comment]
CTDL properties for [CredentialOrganization](https://credreg.net/ctdl/terms/CredentialOrganization#CredentialOrganization) offer numerous options for clarifying the role of the organization in the lifecycle of the credential, of which two obvious examples are "offers" and "owns"-- reference to the CTDL term CredentialOrganization and its properties can provide a rich vocabulary for expressing these relationships

**Comment by justinpitcher** [comment]
WG: blame Alex for the types array in OB2.0.
