### ISSUE TITLE
Should all terms be singular?

### ISSUE THREAD

**Issue by amiller-ims** [IMSGlobal/openbadges-specification#386]
[Verifiable Credentials Data Model 1.1](https://www.w3.org/TR/vc-data-model/) and associated [Context](https://www.w3.org/2018/credentials/v1) use singular form, even for array properties.

Open Badges 2.0 and its associated Context also use singular form, even for array properties.

CLR 1.0 and its associated Context use plural form for array properties.

OB 3.0 has inherited several array properties from CLR 1.0. If we keep the plural terms, the data models and contexts will have a mix: sometimes the singular form is used for arrays, and other times the plural form is used for arrays. This is an antipattern which will likely make adoption of OB 3.0 and CLR 2.0 more difficult.

**Comment by amiller-ims** [comment]
@ottonomy - Would you like to add your thoughts?

**Comment by justinpitcher** [comment]
Group consensus is to stick with singular. Will need to PR a branch with changes to tweak existing plural terms.

**Comment by martyr280** [comment]
+1 from CLR Workgroup

**Comment by amiller-ims** [comment]
Merged in both OB and CLR data models and context files.
