### ISSUE TITLE
Recipient Object Suggestions

### ISSUE THREAD

**Issue by kayaelle** [IMSGlobal/openbadges-specification#393]
Can we consider changing "recipient" to "profile" so that the triple reads more like: "credential subject has profile containing email. Also consider changing the class to an array so that a profile can contain an email, url, and telephone number versus an email or a url or a telephone number.

Example: https://json.link/6b0tEyO3dP

Lastly, telephone number is vague. Should we consider adding https://schema.org/ContactPoint to describe whether it is a mobile number?

**Comment by justinpitcher** [comment]
WG: let's go with `identifier`
