### ISSUE TITLE
Base Doc - Data Model Suggestion for Issuer

### ISSUE THREAD

**Issue by kayaelle** [IMSGlobal/openbadges-specification#408]
Issuer currently references Profile but it should reference the vc spec which defines it as:

"The value of the issuer [property](https://www.w3.org/TR/vc-data-model/#dfn-property) MUST be either a [URI](https://www.w3.org/TR/vc-data-model/#dfn-uri) or an object containing an id [property](https://www.w3.org/TR/vc-data-model/#dfn-property). It is RECOMMENDED that the [URI](https://www.w3.org/TR/vc-data-model/#dfn-uri) in the issuer or its id be one which, if dereferenced, results in a document containing machine-readable information about the [issuer](https://www.w3.org/TR/vc-data-model/#dfn-issuers) that can be used to [verify](https://www.w3.org/TR/vc-data-model/#dfn-verify) the information expressed in the [credential](https://www.w3.org/TR/vc-data-model/#dfn-credential)."

Open Badges can add a Profile to the OpenBadgeCredential but the Issuer shouldn't be a Profile. Suggestion:

issuer->vc spec
issuerProfile->profile

This separates the identity of the issuer from the issuer's profile information.

**Comment by amiller-ims** [comment]
I'd argue for using the Profile object for `issuer` (and `creator`):

- The Profile object has an `id` property so it is compatible with vc-data-model
- OB has used the Profile object for the `issuer` property since the property was introduced
- Products that display OBs know to look in the `issuer` property to find display information about the issuer

**Comment by kayaelle** [comment]
The reason I believe Profile isn't a compatible value for issuer is that issuer is solely and identifier so that it reads as Issuer has this identifier not issuer has this profile. But we could say the VC has an issuerProfile.  The identity id of issuer is critical for alignment because this is the identity signing the VC.

Agree on Profile for creator because VCs don't have a creator value and Profile works fine for this.

**Comment by amiller-ims** [comment]
vc-data-model [Example 11](https://www.w3.org/TR/vc-data-model/#example-usage-of-issuer-expanded-property): 

```
  "issuer": {
    "id": "did:example:76e12ec712ebc6f1c221ebfeb1f",
    "name": "Example University"
  },
```

**Comment by kayaelle** [comment]
Thanks - I just reread that again. Going to close this.
