### ISSUE TITLE
Base Doc - Data Model Suggestion for AchievementCredential

### ISSUE THREAD

**Issue by kayaelle** [IMSGlobal/openbadges-specification#410]
AchievementCredential is an alias to OpenBadgeCredential for CLRv2. Suggestion to change AchievementCredential to OpenBadge credential (see PR https://github.com/IMSGlobal/openbadges-specification/pull/407)

**Comment by danblickensderfer** [comment]
Adressed in #407 which is closed; work group ok with closing
