### ISSUE TITLE
Base Doc - Data Model Suggestion for AchievementCredential (name & description)

### ISSUE THREAD

**Issue by kayaelle** [IMSGlobal/openbadges-specification#411]
Suggest that name & description be removed from AchievementCredential because name & description are located in the Achievement class.

Suggest we keep image at this level because issuers may wish to generate unique images per awarded badges vs. achievement where the image is the same for each awarded badge.

**Comment by amiller-ims** [comment]
`name`, `description`, and `image` were added to AchievementCredential in PR #391. The project group approved and merged the PR on April 28.

**Comment by kayaelle** [comment]
I'll close this one. Thanks!
