### ISSUE TITLE
Achievement Versioning

### ISSUE THREAD

**Issue by kayaelle** [IMSGlobal/openbadges-specification#423]
In Open Badges 2.0 (and I think some earlier versions) there was a model for versioning the BadgeClass: 

"The version property allows issuers to set a version number or string for a BadgeClass. This is particularly useful when replacing a previous version with an update."

`{
  "@context": "https://w3id.org/openbadges/v2",
  "id": "https://example.org/beths-robotics-badge-v2.json",
  "name": "Awesomer Robotics Badge",
  "version": 2,
  "related": {
    "id": "https://example.org/beths-robotics-badge.json",
    "version": 1
  }
}`

Suggestion to have a discussion about the use cases for including this in Achievement.

**Comment by danblickensderfer** [comment]
Open Badges Work Group can take this up in next week's meeting.

Can CLR and OB work groups choose a different path to address this?

Marty: least change is most desirable here

Nate: Proposal: use this issue to discuss using “association" to cover the case for "related previous versions”

**Comment by ottonomy** [comment]
To discuss (with my endorsement): Viktor suggested we restrict the possible value space to string rather than string or number as it was in 2.0
