### ISSUE TITLE
Achievement type

### ISSUE THREAD

**Issue by kayaelle** [IMSGlobal/openbadges-specification#429]
The type property in Achievement is described as required in the base doc but this property isn't needed. AchievementCredential describes the credential as an AchievementCredential/OpenBadgeCredential and achievementType explains what the achievement claim is about. Since Achievement will not be evaluated as its own context as BadgeClasses were, we shouldn't need type.

**Comment by amiller-ims** [comment]
I agree. Achievement `type` is required in OB 2.0, so I added `type` to OB 3.0 Achievement, and made it required. I'll put together a PR that removes the property.

**Comment by ottonomy** [comment]
@kayaelle is the point of this removal just to make the document more brief? You're right that the usage can be implied, but this may be a case of extra data that is worth keeping. 

If `Achievement.id`s are URIs from which OB metadata may be fetched, it would make sense to offer a type on the documents in that context.
