### ISSUE TITLE
Artifact Class

### ISSUE THREAD

**Issue by kayaelle** [IMSGlobal/openbadges-specification#434]
There's an Artifact class that is described as being part of the Evidence object: [https://imsglobal.github.io/openbadges-specification/ob_v3p0.html#artifact](https://imsglobal.github.io/openbadges-specification/ob_v3p0.html#artifact)

but the Evidence object doesn't mention it:

[https://imsglobal.github.io/openbadges-specification/ob_v3p0.html#evidence](https://imsglobal.github.io/openbadges-specification/ob_v3p0.html#evidence)

**Comment by amiller-ims** [comment]
It came from CLR 1.0 and the CLR project group approved removing it. https://github.com/IMSGlobal/ComprehensiveLearnerRecord/issues/291

But I forgot to remove it. I just removed it from the common_credentials.lines file which should kick off a rebuild of the base document.

It can be safely removed from the OB context if it is still there.
