### ISSUE TITLE
Is support for nested/hierarchical contract mandatory ? If so can you help us understand why this is mandatory ?

### ISSUE THREAD

**Issue by premgan** [IMSGlobal/openbadges-specification#448]
Per the spec the OpenBadge VC needs to conform to [this](https://imsglobal.github.io/openbadges-specification/context.json). If there is a  flattened contract rather than a hierarchical/nested contract with the same attributes, will that suffice to conform to this spec, or is support for nested/hierarchical contract mandatory ? If so can you help us understand why this is mandatory ?

**Comment by ottonomy** [comment]
@premgan can you provide an example of the "flattened" data that you are asking would be compliant?

**Comment by premgan** [comment]
@ottonomy My apologies for the delay in the response. Can you share with me a sample Open Badge 3.0 JWOT and I can re-format to show what I mean ?

**Comment by premgan** [comment]
https://github.com/IMSGlobal/openbadges-specification/blob/develop/ob_v3p0/examples/fullOpenBadge.html - Here is an example of the hierarchical/nested contract. 
Lets say:
Instead of:

"credentialSubject": {
...
###       "source": {
        "id": "https://school.edu/issuers/201234",
        "type": ["Profile"],
        "name": "1EdTech College of Arts"
      },
...

We use this: (Basically you will see "type" dropped out and the structure flattened) 

"credentialSubject": {
      ...
 ###      "source-name": "1EdTech College of Arts"
      },

Will we still be compliant with the spec ?

**Comment by ottonomy** [comment]
No, this approach would not be compliant. Verifiers need to see the data in the structure they expect. Allowing too much caution to accomplish the same things makes the spec more expensive to implement in the consumer side, which is something I strongly recommend the workgroup watch out for. Verifiers/consumer support is critical for the ecosystem. Requiring a specific data format for issuers is generally a lot cheaper than forcing consumers to interpret multiple possible formats.
