### ISSUE TITLE
is JSON-LD support mandatory ?

### ISSUE THREAD

**Issue by premgan** [IMSGlobal/openbadges-specification#452]
Follow-up from https://github.com/IMSGlobal/openbadges-specification/issues/447

<html>
<body>
<p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: 16px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><a href="https://imsglobal.github.io/openbadges-specification/ob_v3p0.html#achievementcredential" rel="nofollow" style="box-sizing: border-box; background-color: transparent; color: var(--color-accent-fg); text-decoration: none; transition: color 80ms cubic-bezier(0.33, 1, 0.68, 1) 0s, background-color, box-shadow, border-color;">https://imsglobal.github.io/openbadges-specification/ob_v3p0.html#achievementcredential</a><span> </span>- Is there a reason then why this is the only context specified in the spec ?</p>

Property | Type | Description | Multiplicity
-- | -- | -- | --
@context | URI | The value of the @context property MUST be an ordered set where the first item is a URI with the value 'https://www.w3.org/2018/credentials/v1', and the second item is a URI with the value 'https://purl.imsglobal.org/spec/ob/v3p0/context/ob_v3p0.jsonld'. | [1..*]

<span style="color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">Property Type Description Multiplicity<span> </span></span><a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/context/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/context" style="box-sizing: border-box; background-color: rgb(255, 255, 255); color: var(--color-fg-default); text-decoration: none; transition: color 80ms cubic-bezier(0.33, 1, 0.68, 1) 0s, background-color, box-shadow, border-color; font-weight: 600; white-space: nowrap; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;">@context</a><span style="color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span> </span>[URI](https://imsglobal.github.io/openbadges-specification/ob_v3p0.html#org.1edtech.ob.v3p0.derived.uri.class) The value of the<span> </span></span><a class="user-mention notranslate" data-hovercard-type="user" data-hovercard-url="/users/context/hovercard" data-octo-click="hovercard-link-click" data-octo-dimensions="link_type:self" href="https://github.com/context" style="box-sizing: border-box; background-color: rgb(255, 255, 255); color: var(--color-fg-default); text-decoration: none; transition: color 80ms cubic-bezier(0.33, 1, 0.68, 1) 0s, background-color, box-shadow, border-color; font-weight: 600; white-space: nowrap; margin-bottom: 0px !important; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px;">@context</a><span style="color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"><span> </span>property MUST be an ordered set where the first item is a URI with the value 'https://www.w3.org/2018/credentials/v1', and the second item is a URI with the value 'https://purl.imsglobal.org/spec/ob/v3p0/context/ob_v3p0.jsonld'. [1..*]</span>
</body>
</html>

@ottonomy
Contributor
[ottonomy](https://github.com/ottonomy) commented [18 days ago](https://github.com/IMSGlobal/openbadges-specification/issues/447#issuecomment-1138804799)
From an issuer perspective, it is required for conformance to add the @context property in so that consumers may choose to perform JSON-LD processing on the data. This doesn't imply that the issuers or consumers of this data must perform JSON-LD-specific operations. This is a similar approach to how contexts are handled in the [Verifiable Credentials Data Model](https://w3c.github.io/vc-data-model/#contexts)

We're implementing VC. From the VC spec:

[Verifiable credentials](https://w3c.github.io/vc-data-model/#dfn-verifiable-credentials) and [verifiable presentations](https://w3c.github.io/vc-data-model/#dfn-verifiable-presentations) MUST include a @context [property](https://w3c.github.io/vc-data-model/#dfn-property).

@[ottonomy](https://github.com/ottonomy) ottonomy closed this as [completed](https://github.com/IMSGlobal/openbadges-specification/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [18 days ago](https://github.com/IMSGlobal/openbadges-specification/issues/447#event-6687116577)

[premgan](https://github.com/premgan) commented [18 days ago](https://github.com/IMSGlobal/openbadges-specification/issues/447#issue-1249768307)
Per the spec “Though this specification requires that a @context property be present, it is not required that the value of the @context property be processed using JSON-LD. This is to support processing using plain JSON libraries, such as those that might be used when the verifiable credential is encoded as a JWT.” – So question: is JSON-LD support mandatory ?

**Comment by premgan** [comment]
@ottonomy - Is there JSON equivalent for https://purl.imsglobal.org/spec/ob/v3p0/context/ob_v3p0.jsonld ?

**Comment by ottonomy** [comment]
All JSON-LD is also valid JSON, so implement the `@context` property as described, and you will correctly have done it "in JSON".
