### ISSUE TITLE
Review of Model Open Badge 3.0 for Plugfest 2 & Question About Context File

### ISSUE THREAD

**Issue by kayaelle** [IMSGlobal/openbadges-specification#461]
Hello,

Below is a model of an Open Badge 3.0 for the JFF VC-EDU Plugfest #2. Could we get second eyes on this to make sure that it isn't missing any required elements?  Please ignore the content of the badge. That is still being worked out.

Here's the example:

```json
{
  "@context": [
    "https://www.w3.org/2018/credentials/v1",
    "https://purl.imsglobal.org/spec/ob/v3p0/context.json"
  ],
  "id": "urn:uuid:5f2ecb80-24d5-41b5-8739-538b8faa2f73",
  "type": [
    "VerifiableCredential",
    "OpenBadgeCredential"
  ],
  "issuer": {
    "type": "Profile",
    "id": "did:key:z6MktiSzqF9kqwdU8VkdBKx56EYzXfpgnNPUAGznpicNiWfn",
    "name": "Jobs for the Future (JFF)"
  },
  "issuanceDate": "2022-05-01T00:00:00Z",
  "credentialSubject": {
    "type": "AchievementSubject",
    "id": "did:key:123",
    "achievement": {
      "id": "urn:uuid:dba75453-7a5a-4e3f-96f7-c5a38f64d26d",
      "type": "Achievement",
      "name": "JFF Plugfest #2 2022",
      "description": "Succesfully completed requirements for Plugfest #2",
      "criteria": {
        "type": "Criteria",
        "narrative": "Content here describing reuqirements of plugfest 2"
      },
      "image": "https://w3c-ccg.github.io/vc-ed/plugfest-1-2022/images/plugfest-2-badge-image.png"
    }
  },
  "proof": {
    "type": "Ed25519Signature2018",
    "created": "2022-09-21T13:58:04Z",
    "verificationMethod": "did:key:z6MktiSzqF9kqwdU8VkdBKx56EYzXfpgnNPUAGznpicNiWfn#z6MktiSzqF9kqwdU8VkdBKx56EYzXfpgnNPUAGznpicNiWfn",
    "proofPurpose": "assertionMethod",
    "jws": "eyJhbGciOiJFZERTQSIsImI2NCI6ZmFsc2UsImNyaXQiOlsiYjY0Il19..RdqgwsA6Lc6UpIyHUqGmtmRBSsdrmA7rOR4vZBbxYesUF49xzYD2CiQviznzmGeyd06IimXC6_Elk3pU3WqrDw"
  }
}
```

Right now it contains the context file used for plugfest #1. This file was only to be used temporarily for that plugfest. Now that OBv3 is nearly ready for candidate release, it'd be better to use the correct file.

The context file in the draft spec results in a 404: https://purl.imsglobal.org/spec/ob/v3p0/context/ob_v3p0.jsonld

And the draft file isn't the correct mime type which causes errors for verifiers: https://github.com/IMSGlobal/openbadges-specification/blob/develop/ob_v3p0/context.json

What should we use? Thanks

**Comment by kayaelle** [comment]
Hello @justinpitcher @ottonomy @andyfmiller - Can you please review the example above and provide your feedback before Friday?

**Comment by mgylling** [comment]
@kayaelle, below are the canonical URLs for the contexts. We are updating all inline references in the spec docs to refer to these. Sorry for the confusion. 

https://purl.imsglobal.org/spec/ob/v3p0/context.json
https://purl.imsglobal.org/spec/ob/v3p0/extensions.json
https://purl.imsglobal.org/spec/clr/v2p0/context.json

**Comment by kayaelle** [comment]
Thanks @mgylling! I updated the example above with the new URL.

Looking forward to feedback.

**Comment by andyfmiller** [comment]
I used [JSON Schema Validator by Newtonsoft](https://www.jsonschemavalidator.net/) to check the example against the canonical JSON Schema at https://purl.imsglobal.org/spec/ob/v3p0/schema/json/ob_v3p0_achievementcredential_schema.json. The validator identified several errors: https://www.jsonschemavalidator.net/s/4zk7atnN

**Comment by kayaelle** [comment]
Thank you @andyfmiller.
